=== HonghongLu/CH554/taobao ch554/C# library application examples written in LIBUSB/Docs/tree.dtd
<!ELEMENT assembly (tree+)>
<!ATTLIST assembly name CDATA #REQUIRED>
<!ATTLIST assembly version CDATA #REQUIRED>
<!ELEMENT tree (branch+)>
<!ELEMENT branch (branchText,(branch|leaf)*)>
<!ATTLIST branch id CDATA #REQUIRED>
<!ATTLIST branch children CDATA #REQUIRED>
<!ELEMENT branchText (#PCDATA)>
<!ATTLIST branchText ObjectType CDATA "">
<!ELEMENT leaf (leafText,link,javaLink)>
<!ELEMENT leafText (#PCDATA)>
<!ELEMENT link (#PCDATA)>
<!ELEMENT javaLink (#PCDATA)>

=== HonghongLu/CH554/taobao ch554/C# library application examples written in LIBUSB/Docs/LibUsbDotNet.xml
<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet type='text/xsl' href='xmlTree.xsl'?>
<!DOCTYPE assembly SYSTEM "tree.dtd">
<!--Auto-Generated by NetDocumentor-->
<!--Reflector Plugin. http://www.aisto.com/roeder/dotnet-->
<assembly name="LibUsbDotNet" version="1.0.1">
  <tree>
    <branch children="1" id="NS:LibUsbDotNet.DeviceNotify">
      <branchText ObjectType="Namespace">LibUsbDotNet.DeviceNotify</branchText>
      <branch children="1" id="key1">
        <branchText ObjectType="Class">DeviceNotifier</branchText>
        <branch children="0" id="G:LibUsbDotNet.DeviceNotify.DeviceNotifier+Constructors">
          <branchText>Constructors</branchText>
        </branch>
        <branch children="1" id="G:LibUsbDotNet.DeviceNotify.DeviceNotifier+Events">
          <branchText>Events</branchText>
          <branch children="0" id="key9">
            <branchText>OnDeviceNotify</branchText>
          </branch>
        </branch>
      </branch>
      <branch children="1" id="key46">
        <branchText ObjectType="Class">DeviceNotifyEventArgs</branchText>
        <branch children="1" id="G:LibUsbDotNet.DeviceNotify.DeviceNotifyEventArgs+Methods">
          <branchText>Methods</branchText>
          <branch children="0" id="key53">
            <branchText>ToString</branchText>
          </branch>
        </branch>
        <branch children="1" id="G:LibUsbDotNet.DeviceNotify.DeviceNotifyEventArgs+Properties">
          <branchText>Properties</branchText>
          <branch children="0" id="key59">
            <branchText>Device</branchText>
          </branch>
          <branch children="0" id="key61">
            <branchText>DeviceType</branchText>
          </branch>
          <branch children="0" id="key60">
            <branchText>EventType</branchText>
          </branch>
          <branch children="0" id="key62">
            <branchText>Object</branchText>
          </branch>
          <branch children="0" id="key58">
            <branchText>Port</branchText>
          </branch>
          <branch children="0" id="key57">
            <branchText>Volume</branchText>
          </branch>
        </branch>
      </branch>
      <branch children="0" id="key10">
        <branchText ObjectType="Enumeration">DeviceType</branchText>
      </branch>
      <branch children="0" id="key28">
        <branchText ObjectType="Enumeration">EventType</branchText>
      </branch>
    </branch>
    <branch children="1" id="NS:LibUsbDotNet.DeviceNotify.Info">
      <branchText ObjectType="Namespace">LibUsbDotNet.DeviceNotify.Info</branchText>
      <branch children="1" id="key63">
        <branchText ObjectType="Class">PortNotifyInfo</branchText>
        <branch children="1" id="G:LibUsbDotNet.DeviceNotify.Info.PortNotifyInfo+Methods">
          <branchText>Methods</branchText>
          <branch children="0" id="key65">
            <branchText>ToString</branchText>
          </branch>
        </branch>
        <branch children="1" id="G:LibUsbDotNet.DeviceNotify.Info.PortNotifyInfo+Properties">
          <branchText>Properties</branchText>
          <branch children="0" id="key69">
            <branchText>Name</branchText>
          </branch>
        </branch>
      </branch>
      <branch children="1" id="key70">
        <branchText ObjectType="Class">UsbDeviceNotifyInfo</branchText>
        <branch children="1" id="G:LibUsbDotNet.DeviceNotify.Info.UsbDeviceNotifyInfo+Methods">
          <branchText>Methods</branchText>
          <branch children="0" id="key77">
            <branchText>ToString</branchText>
          </branch>
        </branch>
        <branch children="1" id="G:LibUsbDotNet.DeviceNotify.Info.UsbDeviceNotifyInfo+Properties">
          <branchText>Properties</branchText>
          <branch children="0" id="key83">
            <branchText>ClassGuid</branchText>
          </branch>
          <branch children="0" id="key85">
            <branchText>IdProduct</branchText>
          </branch>
          <branch children="0" id="key84">
            <branchText>IdVendor</branchText>
          </branch>
          <branch children="0" id="key82">
            <branchText>Name</branchText>
          </branch>
          <branch children="0" id="key86">
            <branchText>SerialNumber</branchText>
          </branch>
          <branch children="0" id="key81">
            <branchText>SymbolicName</branchText>
          </branch>
        </branch>
      </branch>
      <branch children="1" id="key87">
        <branchText ObjectType="Class">VolumeNotifyInfo</branchText>
        <branch children="1" id="G:LibUsbDotNet.DeviceNotify.Info.VolumeNotifyInfo+Methods">
          <branchText>Methods</branchText>
          <branch children="0" id="key93">
            <branchText>ToString</branchText>
          </branch>
        </branch>
        <branch children="1" id="G:LibUsbDotNet.DeviceNotify.Info.VolumeNotifyInfo+Properties">
          <branchText>Properties</branchText>
          <branch children="0" id="key98">
            <branchText>ChangeAffectsMediaInDrive</branchText>
          </branch>
          <branch children="0" id="key100">
            <branchText>Flags</branchText>
          </branch>
          <branch children="0" id="key99">
            <branchText>IsNetworkVolume</branchText>
          </branch>
          <branch children="0" id="key97">
            <branchText>Letter</branchText>
          </branch>
          <branch children="0" id="key101">
            <branchText>Unitmask</branchText>
          </branch>
        </branch>
      </branch>
    </branch>
    <branch children="1" id="NS:LibUsbDotNet.Usb">
      <branchText ObjectType="Namespace">LibUsbDotNet.Usb</branchText>
      <branch children="1" id="key534">
        <branchText ObjectType="Class">UsbDevice</branchText>
        <branch children="1" id="G:LibUsbDotNet.Usb.UsbDevice+Methods">
          <branchText>Methods</branchText>
          <branch children="0" id="key539">
            <branchText>ClaimInterface</branchText>
          </branch>
          <branch children="0" id="key540">
            <branchText>Close</branchText>
          </branch>
          <branch children="0" id="key541">
            <branchText>GetAltInterface</branchText>
          </branch>
          <branch children="0" id="key542">
            <branchText>GetConfiguration</branchText>
          </branch>
          <branch children="0" id="key543">
            <branchText>GetString</branchText>
          </branch>
          <branch children="0" id="key544">
            <branchText>GetString</branchText>
          </branch>
          <branch children="0" id="key545">
            <branchText>IOControlMessage</branchText>
          </branch>
          <branch children="0" id="key546">
            <branchText>Open</branchText>
          </branch>
          <branch children="0" id="key548">
            <branchText>OpenBulkEndpointReader</branchText>
          </branch>
          <branch children="0" id="key547">
            <branchText>OpenBulkEndpointReader</branchText>
          </branch>
          <branch children="0" id="key549">
            <branchText>OpenBulkEndpointWriter</branchText>
          </branch>
          <branch children="0" id="key550">
            <branchText>OpenEndpointReader</branchText>
          </branch>
          <branch children="0" id="key551">
            <branchText>OpenEndpointWriter</branchText>
          </branch>
          <branch children="0" id="key553">
            <branchText>OpenInterruptEndpointReader</branchText>
          </branch>
          <branch children="0" id="key552">
            <branchText>OpenInterruptEndpointReader</branchText>
          </branch>
          <branch children="0" id="key554">
            <branchText>OpenInterruptEndpointWriter</branchText>
          </branch>
          <branch children="0" id="key555">
            <branchText>RefreshConfigs</branchText>
          </branch>
          <branch children="0" id="key556">
            <branchText>ReleaseInterface</branchText>
          </branch>
          <branch children="0" id="key557">
            <branchText>SetAltInterface</branchText>
          </branch>
          <branch children="0" id="key558">
            <branchText>SetConfiguration</branchText>
          </branch>
        </branch>
        <branch children="1" id="G:LibUsbDotNet.Usb.UsbDevice+Properties">
          <branchText>Properties</branchText>
          <branch children="0" id="key563">
            <branchText>ActiveEndpoints</branchText>
          </branch>
          <branch children="0" id="key565">
            <branchText>Configs</branchText>
          </branch>
          <branch children="0" id="key564">
            <branchText>Info</branchText>
          </branch>
          <branch children="0" id="key566">
            <branchText>IsOpen</branchText>
          </branch>
        </branch>
      </branch>
      <branch children="1" id="key446">
        <branchText ObjectType="Class">UsbEndpointBase</branchText>
        <branch children="1" id="G:LibUsbDotNet.Usb.UsbEndpointBase+Methods">
          <branchText>Methods</branchText>
          <branch children="0" id="key451">
            <branchText>CancelIO</branchText>
          </branch>
          <branch children="0" id="key452">
            <branchText>Dispose</branchText>
          </branch>
          <branch children="0" id="key453">
            <branchText>Transfer</branchText>
          </branch>
        </branch>
        <branch children="1" id="G:LibUsbDotNet.Usb.UsbEndpointBase+Properties">
          <branchText>Properties</branchText>
          <branch children="0" id="key460">
            <branchText>EndpointType</branchText>
          </branch>
          <branch children="0" id="key459">
            <branchText>EpNum</branchText>
          </branch>
          <branch children="0" id="key458">
            <branchText>IsDisposed</branchText>
          </branch>
          <branch children="0" id="key461">
